spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Initial0

  redis:
    database: 0
    host: localhost
    port: 6379

  cache:
    type: REDIS
    redis:
      time-to-live: 1d
      use-key-prefix: true

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  show-sql: true


server:
  port: 8080

logging:
  level:
    root: INFO
  file:
    name: log/spring-boot-demo.log